baseURL: https://www.nagata.pro
languageCode: ja-JP
title: ã©ã†ã‚‚ã€ãªãŒãŸã§ã™
author: ãªãŒãŸ
defaultContentLanguage: ja
theme: PaperMod

ShowToc: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

languages:
  ja:
    languageName: ":ja:"
    weight: 1

  en:
    languageName: ":en:"
    weight: 2
    title: Hi there, I'm Nagata
    author: Nagata
    Projects:
      github:
        url: https://api.github.com/users/nagataaaas/repos?type=owner&sort=updated&per_page=100
      other:
        projects:
          - name: Widget to display wind direction/speed/time in GUI
            description: This widget displays information observed by [Usuda Deep Space Center](https://global.jaxa.jp/about/centers/udsc/index.html) in GUI in conjunction with [Zabbix](https://www.zabbix.com/). It is actually used at Usuda Deep Space Center.
          - name: A product that can create advertisements with node-based programming language
            description: non-programmers can easily create contextual advertising services
          - name: Scraping
            description: I have created a program for scraping various e-commerce sites, newspapers, horse racing, NBA, etc.
          - name: Food delivery service
            description: >
              Created backend and part of the frontend of a food delivery service. \
              
              [MySQL](https://www.mysql.com/) / [FastAPI](https://fastapi.tiangolo.com/) / 
              GoogleAPIs [GeoCoding](https://developers.google.com/maps/documentation/geocoding/overview), 
              [Directions](https://developers.google.com/maps/documentation/directions/overview), 
              [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/overview) are used
          - name: Code Review
            description: reviewing code for many customers, sometimes even writing entire programs for them
          - name: Business improvement
            description: Improved efficiency by automating business processes and changing the input of business information to a GUI-based application.
          - name: Bringing services online
            description: I have made some services more user-friendly by converting customer's own excel files or scripts into online services.
          - name: Electric bulletin board style information display
            description: A product that displays various information using html/css + JavaScript in the style of an electric bulletin board.

    Params:
      homeInfoParams:
        Title: NagatağŸ±
        Content: >
          I am an IT engineer. I've worked mainly on the backend, \
          
          but I'll also work on the frontend **with tears in my eyes** when it's needed.\
          
          I love **Python** and many other things. I've been using it for more than 10 years.\
          
          I'm Nagata.
        imageUrl: "/image/lemon.jpg"
      Career:
        - name: DeNA
          position: ENGINEER
          from: "Apr 2022"
          until: " "
          description: >
            I join(ed) the company as a newly graduated engineer.
        - name: Intern at DeNA
          position: BACKEND DEVELOPER
          from: "Jan 2021"
          until: "Aug 2021"
          description: >
            It was extremely difficult because I had to develop an actual launched application in a language and 
            environment that I was dealing with for the first time, but it broadened my perspective as an engineer.
        - name: Intern at DeNA
          position: BACKEND DEVELOPER
          from: "Aug 2019"
          until: ""
          description: >
            It was the first step toward a more practical engineering career, 
            and an important factor in determining my future career path.
        - name: Intern at LINE
          position: BACKEND DEVELOPER
          from: "Aug 2018"
          until: "Sep 2018"
          description: >
            It was my first experience in creating a medium or larger scale product, and although there were 
            many things I did not understand, it was an opportunity to learn the true beauty of programming.
        - name: Freelance Programmer
          position: FULL STACK DEVELOPER
          from: "Apr 2017"
          until: "Present"
          description: >
            I am a freelance programmer. I have done a variety of projects to enhance my abilities.



Params:
#  env: production
  ContactFormURL: https://getform.io/f/354d83f8-2000-47fd-9e2a-01bc902b5363
  Skills:
    Tech:
      IntermediateAdvanced: [ Python, JavaScript, Go,C, C++, Kotlin, HTML5/CSS3, SQL ]
      CanHandleSomehow: [ Rust, Julia, Swift, Java ]
    Language:
      Fluent: [Japanese]
      Business: [English]
  displayFullLangName: false
  ShowCodeCopyButtons: true
  assets:
    favicon: /icon/favicon.ico
    favicon16x16: /icon/favicon-16x16.png
    favicon32x32: /icon/favicon-32x32.png
    apple_touch_icon: /icon/apple-touch-icon.png
    safari_pinned_tab: /icon/safari-pinned-tab.svg
    theme_color: '#ffffff'
    msapplication_TileColor: '#da532c'
  images:
    - /image/lemon.jpg
  customCss:
    - css/top.css
  ShowReadingTime: true
  homeInfoParams:
    Title: ãªãŒãŸğŸ±
    Content: >
      ITã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã§ã™ã€‚ä¸»ã«ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰æ‹…å½“ã‚’çµŒé¨“ã—ã¦ãã¾ã—ãŸãŒ\
      
      ãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰ã‚‚å¿…è¦ã«è¿«ã‚‰ã‚ŒãŸæ™‚ã¯**æ¶™ã‚’æµã—ãªãŒã‚‰**å¯¾å¿œã—ã¾ã™\
      
      **Python**ã¨ã‹ã„ã‚ã„ã‚å¥½ãã§ã™ã€‚ã‹ã‚Œã“ã‚Œ10å¹´ãŠä¸–è©±ã«ãªã£ã¦ã„ã¾ã™\
      
      ãªãŒãŸã§ã™
    imageUrl: "/image/lemon.jpg"
  ShowShareButtons: true
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/nagataaaas"
    - name: "email"
      url: "mailto:nagata@nagata.pro"
    - name: "twitter"
      url: "https://twitter.com/514YJ"

  Projects:
    github:
      url: https://api.github.com/users/nagataaaas/repos?type=owner&sort=updated&per_page=100
    other:
      projects:
        - name: é¢¨å‘/é¢¨é€Ÿ/æ™‚åˆ»ã‚’GUIã§è¡¨ç¤ºã™ã‚‹ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆ
          description: >
            [è‡¼ç”°å®‡å®™ç©ºé–“è¦³æ¸¬æ‰€](https://www.jaxa.jp/about/centers/udsc/index_j.html)ã§è¦³æ¸¬ã—ãŸæƒ…å ±ã‚’ã€[Zabbix](https://www.zabbix.com/jp)ã¨é€£æºã—ã¦GUIã§è¡¨ç¤ºã™ã‚‹ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã§ã™\
            
            å®Ÿéš›ã«è‡¼ç”°å®‡å®™ç©ºé–“è¦³æ¸¬æ‰€ã§ç”¨ã„ã‚‰ã‚Œã¦ã„ã¾ã™
        - name: ãƒãƒ¼ãƒ‰ãƒ™ãƒ¼ã‚¹ã§åºƒå‘Šã‚’ä½œæˆã§ãã‚‹ãƒ—ãƒ­ãƒ€ã‚¯ãƒˆ
          description: ãƒãƒ³ãƒ—ãƒ­ã‚°ãƒ©ãƒãƒ¼ã§ã‚‚ç°¡å˜ã«ã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆã®ã‚ã‚‹åºƒå‘Šã‚µãƒ¼ãƒ“ã‚¹ã‚’ä½œæˆã§ãã¾ã™
        - name: ã‚¹ã‚¯ãƒ¬ã‚¤ãƒ”ãƒ³ã‚°
          description: æ§˜ã€…ãªECã‚µã‚¤ãƒˆã‚„æ–°èã€ç«¶é¦¬ã€NBAãªã©ã®ã‚¹ã‚¯ãƒ¬ã‚¤ãƒ”ãƒ³ã‚°ã‚’è¡Œã†ãƒ—ãƒ­ã‚°ãƒ©ãƒ ã‚’ä½œæˆã—ã¾ã—ãŸ
        - name: ãƒ•ãƒ¼ãƒ‰ãƒ‡ãƒªãƒãƒªãƒ¼ã‚µãƒ¼ãƒ“ã‚¹
          description: >
            ãƒ•ãƒ¼ãƒ‰ãƒ‡ãƒªãƒãƒªãƒ¼ã‚µãƒ¼ãƒ“ã‚¹ã®ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ãŠã‚ˆã³ãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰ã®ä¸€éƒ¨ã‚’ä½œæˆã—ã¾ã—ãŸã€‚\
            
            [MySQL](https://www.mysql.com/ja) / [FastAPI](https://fastapi.tiangolo.com/) / 
            GoogleAPIs [GeoCoding](https://developers.google.com/maps/documentation/geocoding/overview), 
            [Directions](https://developers.google.com/maps/documentation/directions/overview), 
            [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/overview?hl=ja-JP) ã‚’åŸºå¹¹ã«ç”¨ã„ã¦ã„ã¾ã™
        - name: ã‚³ãƒ¼ãƒ‰ãƒ¬ãƒ“ãƒ¥ãƒ¼
          description: å¤šãã®ã‚«ã‚¹ã‚¿ãƒãƒ¼ã®ã‚³ãƒ¼ãƒ‰ã®ãƒ¬ãƒ“ãƒ¥ãƒ¼ç­‰ã‚’è¡Œã„ã€ãƒ—ãƒ­ã‚°ãƒ©ãƒ ã®ä½œæˆã¾ã§ã™ã‚‹ã“ã¨ã‚‚ã‚ã‚Šã¾ã™
        - name: æ¥­å‹™æ”¹å–„
          description: æ¥­å‹™ã§ç”¨ã„ã‚‹å‡¦ç†ã‚’è‡ªå‹•åŒ–ã—ãŸã‚Šã€å…¥åŠ›ã‚’GUIãƒ™ãƒ¼ã‚¹ã®ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã«å¤‰æ›´ã™ã‚‹ã“ã©ã§ã€åŠ¹ç‡åŒ–ã‚’å›³ã‚Šã¾ã—ãŸ
        - name: ã‚µãƒ¼ãƒ“ã‚¹ã®ã‚ªãƒ³ãƒ©ã‚¤ãƒ³åŒ–
          description: ã‚«ã‚¹ã‚¿ãƒãƒ¼ãŒè‡ªä½œã—ãŸã‚¨ã‚¯ã‚»ãƒ«ãƒ•ã‚¡ã‚¤ãƒ«ãªã©ã‚’ã€ã‚ªãƒ³ãƒ©ã‚¤ãƒ³åŒ–ã™ã‚‹ã“ã¨ã§ã‚ˆã‚Šãƒ¦ãƒ¼ã‚¶ãƒ•ãƒ¬ãƒ³ãƒ‰ãƒªãƒ¼ãªã‚µãƒ¼ãƒ“ã‚¹ã«ã—ã¾ã—ãŸ
        - name: é›»å…‰æ²ç¤ºæ¿é¢¨æƒ…å ±è¡¨ç¤º
          description: html/css + JavaScriptã‚’ç”¨ã„ã¦ã€æ§˜ã€…ãªæƒ…å ±ã‚’é›»å…‰æ²ç¤ºæ¿é¢¨ã«è¡¨ç¤ºã™ã‚‹ãƒ—ãƒ­ãƒ€ã‚¯ãƒˆ
  Career:
    - name: DeNA
      position: an ENGINEER
      from: "Apr 2022"
      until: " "
      description: >
        æ–°å’ã§ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¨ã—ã¦å…¥ç¤¾ã—ã¾ã™ã€‚
    - name: Intern at DeNA
      position: a BACKEND DEVELOPER
      from: "Jan 2021"
      until: "Aug 2021"
      description: >
        å®Ÿéš›ã«ãƒ­ãƒ¼ãƒ³ãƒã•ã‚Œã‚‹ã‚¢ãƒ—ãƒªã‚’åˆã‚ã¦æ‰±ã†è¨€èªãƒ»ç’°å¢ƒã§é–‹ç™ºã™ã‚‹ãŸã‚éå¸¸ã«ãƒãƒ¼ãƒ‰ãƒ«ãŒé«˜ã‹ã£ãŸã§ã™ãŒã€ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¨ã—ã¦ã®è¦–é‡ãŒåºƒãŒã‚Šã¾ã—ãŸã€‚
    - name: Intern at DeNA
      position: a BACKEND DEVELOPER
      from: "Aug 2019"
      until: ""
      description: >
        ã‚ˆã‚Šå®Ÿè·µçš„ãªã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒªãƒ³ã‚°ã¸ã®è¶³ãŒã‹ã‚Šã¨ãªã‚Šã€ä»¥é™ã®é€²è·¯ã‚’æ±ºã‚ã‚‹é‡è¦ãªãƒ•ã‚¡ã‚¯ã‚¿ãƒ¼ã«ãªã‚Šã¾ã—ãŸã€‚
    - name: Intern at LINE
      position: a BACKEND DEVELOPER
      from: "Aug 2018"
      until: "Sep 2018"
      description: >
        åˆã‚ã¦ä¸­è¦æ¨¡ä»¥ä¸Šã®ãƒ—ãƒ­ãƒ€ã‚¯ãƒˆã‚’åˆ¶ä½œã™ã‚‹çµŒé¨“ã§ã‚ã‹ã‚‰ãªã„ã“ã¨ã ã‚‰ã‘ã§ã—ãŸãŒã€æ¥­å‹™ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ã®ç´ æ™´ã‚‰ã—ã•ã‚’çŸ¥ã‚‹æ©Ÿä¼šã¨ãªã‚Šã¾ã—ãŸã€‚
    - name: Freelance Programmer
      position: a FULL STACK DEVELOPER
      from: "Apr 2017"
      until: "Present"
      description: >
        ãƒ•ãƒªãƒ¼ãƒ©ãƒ³ã‚¹ã¨ã—ã¦ãƒ—ãƒ­ã‚°ãƒ©ãƒ æ¥­å‹™ã‚’è¡Œã£ã¦ã„ã¾ã™ã€‚è‡ªåˆ†ã®èƒ½åŠ›ã‚’é«˜ã‚ã‚‹ãŸã‚ã€æ§˜ã€…ãªæ¡ˆä»¶ã‚’è¡Œã£ã¦ãã¾ã—ãŸã€‚


#  editPost:
#    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: github
      name: GitHub
      url: https://github.com/nagataaaas
      weight: 60
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/514YJ
      weight: 70


markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series

caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 0